### ISSUE TITLE
XIV deck is gone from my plugin list but says its installed

### ISSUE THREAD

**Issue by BeezlyJackal** [KazWolfe/XIVDeck#20] opened 2022-05-25 20:44 UTC
I think I've downloaded every single update for XIV deck as they came out, which may be what is causing this but I'm not sure.

XIV deck doesn't show in my plugins list anymore and my buttons are corrupted. when I go to reinstall the latest version of XIV deck, it says its already installed, and XIV deck doesn't even show in the stream deck directory

**Comment by KazWolfe** [comment] 2022-05-26 03:56
Hi! Thanks for reporting this issue; I'm sorry to hear that you're having troubles with XIVDeck.

This issue appears as though it's caused by the Stream Deck software, so most of this troubleshooting will be focused on that. Please try the below steps, checking to see if the issue is resolved after each step.

1. Fully restart your computer and check the Stream Deck application to see if XIVDeck either returns or is marked as properly uninstalled.
2. Try manually uninstalling the XIVDeck plugin by performing the following steps:
    1. Fully close the Stream Deck application by right-clicking on its icon in your Notification Tray and choosing *Quit Stream Deck*.
    2. Open the Run dialog by pressing Win+R on your keyboard.
    3. Type `%APPDATA%\Elgato\StreamDeck\Plugins` and click OK.
    4. Delete the folder `dev.wolf.xivdeck.sdPlugin` if it exists.
    5. Try reinstalling the XIVDeck Stream Deck plugin.
3. Fully uninstall and reinstall the Stream Deck application from your computer.

If you're still having problems installing and using XIVDeck, it may be necessary to engage Elgato's support in order to fix this particular issue. Until then, though, please try the above steps.

Lastly, to your point, XIVDeck is not published in the official Elgato Plugin Store. This is an intentional decision as this plugin is still undergoing active development and I need to be able to make changes quickly without waiting for Elgato. Similarly, as mods for Final Fantasy XIV are *technically* against the game's Terms of Service, I do not know if Elgato would be willing to accept such a plugin.

If you need any other help or the above steps didn't work for you, please don't hesitate to reach out!

**Comment by BeezlyJackal** [comment] 2022-05-26 04:05
i was looking in program files and not appdata, that would be why. thanks for the help that fixed it!

**Comment by KazWolfe** [comment] 2022-05-26 05:00
Awesome, glad to hear! I'll close out this issue now.

**Closed as completed by KazWolfe** 2022-05-26 05:00 UTC
Labels: Stream Deck plugin
