### ISSUE TITLE
Spamming Text Command Crashes the Game

### ISSUE THREAD

**Issue by ghost** [KazWolfe/XIVDeck#32] opened 2022-10-03 17:52 UTC
I have a Text Command set up on my Stream Deck that (un)mutes my systemsounds. When spamming the Button it crashes the game completly.
The command is just /systemsounds

Didnt test if this is now command specific but Im just assuming no because that would be really weird

**Comment by KazWolfe** [comment] 2022-10-03 18:54
Hi! Thanks for the report, I'm going to mark this as a duplicate of #31 as I strongly suspect the root cause is similar.

A change to Dalamud that should allay this bug was recently merged; assuming all goes well you should see a resolution to this bug within the next couple Dalamud releases.

Thanks!

**Closed as not planned by KazWolfe** 2022-10-03 18:54 UTC
